# основные настройки
avatars:
  default_count: 5

# документация
docs:
  api:
    description: "Документация API мессенджера w1tish для удобства разработки"

  auth:
    summary: "Авторизировать пользователя"
    description: "Получить `access` & `refresh(cookie)` токены с помощью пароля и логина пользователя"
    responses:
      200:
        description: "Токен успешно выдан"
      401:
        description: "Неправильный логин или пароль"
      404:
        description: "Пользователь ещё не зарегестрирован"
      422:
        description: "Неверный формат тела"

  register:
    summary: "Зарегестрировать пользователя"
    description: "Зарегестрировать нового пользователя с помощью пароля логина и почты и получить `access` & `refresh(cookie)` токены"
    responses:
      201:
        description: "Пользователь успешно зарегестрирован"
      409:
        description: "Пользователь уже зарегестрирован"
      422:
        description: "Неверный формат тела"
      
  refresh:
    summary: "Обновить access токен"
    description: "Обновить `access` токен используя `refresh` токен из куки"
    responses:
      200:
        description: "Токен успешно обновлён"
      401:
        description: "Токен просрочен / Нет токена"
      422:
        description: "Неверный формат токена"

  logout:
    summary: "Удалить refresh токен"
    description: "Удалить `refresh` токен из куки и добавить его в чёрный список"
    responses:
      200:
        description: "Токен успешно удалён"
      401:
        description: "Токен просрочен / Нет токена"
      422:
        description: "Неверный формат токена"

  user:
    summary: "Получить данные пользователей"
    description: "Получить данные одного или нескольких пользователей используя айди или логины"
    responses:
      200:
        description: "Данные успешно получены"
      401:
        description: "Токен просрочен / Нет токена"
      422:
        description: "Неверный формат тела / токена"

  data:
    summary: "Получить свои данные"
    description: "Получить данные текущего пользователя включая метаданные чатов"
    responses:
      200:
        description: "Данные успешно получены"
      401:
        description: "Токен просрочен / Нет токена"
      422:
        description: "Неверный формат токена"

  get_messages:
    summary: "Получить историю сообщений в чате"
    description: "Получить историю сообщений в чате по айди с поддержной пагинации"
    responses:
      200:
        description: "Данные успешно получены"
      401:
        description: "Токен просрочен / Нет токена"
      403:
        description: "Пользователь не имеет прав на чтение"
      422:
        description: "Неверный формат токена / неправильные аргументы"

  add_messages:
    summary: "Добавить новое сообщение"
    description: "Отправить сообщение напрямую в базу"
    responses:
      201:
        description: "Сообщение успешно отправлено"
      401:
        description: "Токен просрочен / Нет токена"
      403:
        description: "Пользователь не имеет прав на запись"
      422:
        description: "Неверный формат тела / токена"

  chats:
    summary: "Создать новый чат или группу"
    description: "Создать группу из 2х и более пользователей (до 7)"
    responses:
      201:
        description: "Чат успешно создан"
      401:
        description: "Токен просрочен / Нет токена"
      409:
        description: "Чат уже существует"
      422:
        description: "Неверный формат тела / токена"

  avatar:
    summary: "Изменить аватар пользователя"
    description: "Обработать и загрузить новый аватар пользователя в s3 хранилище"
    responses:
      200:
        description: "Аватар успешно загружен"
      401:
        description: "Токен просрочен / Нет токена"
      413:
        description: "Файл слишком большой"
      422:
        description: "Неверный формат тела / токена"

  config:
    summary: "Получить необходимые переменные"
    description: "Получить адресс бэкэнда и адресс s3 хранилища"

  health:
    summary: "Проверить работоспособность бэкэнда"

# настройки UI swagger
swagger:
  defaultModelsExpandDepth: -1
  filter: true
  